import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    gradientContainer: {
        flex: 1,
    },
    safeArea: {
        flex: 1,
        paddingHorizontal: 20,
        justifyContent: 'center',
    },
    formContainer: {
        width: '100%',
        borderRadius: 28,
        paddingVertical: 32,
        paddingHorizontal: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
    },
    logoContainer: {
        alignItems: 'center',
        marginBottom: 20,
    },
    logo: {
        width: 120,
        height: 176,
        resizeMode: 'contain',
    },
    title: {
        fontSize: 34,
        fontWeight: '800',
        color: '#fff',
        textAlign: 'center',
        letterSpacing: 1,
        marginBottom: 8,
    },
    description: {
        fontSize: 15,
        lineHeight: 22,
        color: '#FFECEC',
        textAlign: 'center',
        marginBottom: 28,
        fontWeight: '500',
    },
    input: {
        width: '100%',
        height: 50,
        backgroundColor: 'rgba(255, 255, 255, 0.94)',
        marginBottom: 15,
        paddingHorizontal: 15,
        borderRadius: 14,
        fontSize: 16,
        color: '#333',
    },
    errorText: {
        color: '#FFE3E3',
        fontSize: 14,
        marginTop: -4,
        marginBottom: 14,
        textAlign: 'center',
        fontWeight: '600',
    },
    loginButton: {
        height: 50,
        backgroundColor: '#FFD700',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 14,
        marginTop: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    loginButtonText: {
        color: '#8B0000',
        fontSize: 18,
        fontWeight: 'bold',
    },
    helperCard: {
        marginTop: 24,
        padding: 16,
        borderRadius: 18,
        backgroundColor: 'rgba(0, 0, 0, 0.18)',
    },
    helperTitle: {
        color: '#FFD700',
        fontSize: 16,
        fontWeight: '700',
        marginBottom: 8,
        textAlign: 'center',
    },
    helperText: {
        color: '#FFF4F4',
        fontSize: 14,
        textAlign: 'center',
        marginBottom: 4,
    },
});
