import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#ffffff',
    },
    navBarHeader: {
        flexDirection: 'row',
        height: 60,
        backgroundColor: '#CC0000',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 15,
        zIndex: 10,
    },
    logo: {
        width: 100,
        height: 40,
    },
    avatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#FFF',
    },
    userInfoBox: {
        position: 'absolute',
        top: 70,
        right: 15,
        backgroundColor: '#FFF',
        padding: 15,
        borderRadius: 8,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        zIndex: 20,
        alignItems: 'center',
    },
    userInfoText: {
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#333',
    },
    logoutButton: {
        backgroundColor: '#F00',
        paddingVertical: 6,
        paddingHorizontal: 15,
        borderRadius: 4,
    },
    logoutButtonText: {
        color: '#FFF',
        fontWeight: 'bold',
        fontSize: 12,
    },
    scrollContent: {
        padding: 16,
        paddingBottom: 40,
    },
    warningText: {
        color: '#d9534f',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 16,
    },
    uploadSection: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    uploadBtn: {
        backgroundColor: '#5bc0de',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 4,
    },
    uploadBtnText: {
        color: '#fff',
        fontWeight: 'bold',
    },
    uploadHint: {
        marginLeft: 10,
        color: '#777',
        fontStyle: 'italic',
    },
    searchSection: {
        backgroundColor: '#f9f9f9',
        padding: 12,
        borderRadius: 8,
        marginBottom: 16,
    },
    searchInput: {
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 4,
        padding: 8,
        marginBottom: 10,
        backgroundColor: '#fff',
        color: '#333',
    },
    filtersRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginBottom: 10,
    },
    pickerBtn: {
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 4,
        padding: 8,
        backgroundColor: '#fff',
    },
    pickerBtnText: {
        color: '#333',
    },
    searchBtn: {
        backgroundColor: '#0275d8',
        padding: 10,
        borderRadius: 4,
        alignItems: 'center',
    },
    searchBtnText: {
        color: '#fff',
        fontWeight: 'bold',
    },
    tableSection: {
        marginTop: 10,
    },
    tableRow: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderColor: '#eee',
    },
    tableHeader: {
        backgroundColor: '#f0f0f0',
        borderBottomWidth: 2,
        borderColor: '#ccc',
    },
    cell: {
        width: 100,
        padding: 10,
        borderRightWidth: 1,
        borderColor: '#eee',
        textAlign: 'center',
        fontSize: 12,
        color: '#333',
    },
    headerCell: {
        fontWeight: 'bold',
    },
    actionCell: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: 120,
        alignItems: 'center',
    },
    editBtn: {
        backgroundColor: '#f0ad4e',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    deleteBtn: {
        backgroundColor: '#d9534f',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    actionText: {
        color: '#fff',
        fontSize: 12,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: '#fff',
        width: '80%',
        maxHeight: '60%',
        borderRadius: 8,
        padding: 10,
    },
    modalItem: {
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    modalItemText: {
        fontSize: 16,
        color: '#333',
        textAlign: 'center',
    },
});
